services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ft_transcendence
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: development # cambiar a "production" 
    container_name: ft_transcendence_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:pgpass@db:5432/transcendence
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev #no hace build completo cada cambio

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development #cambiar a "production"
    container_name: transcendence_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data: