{
 "title": "Dashboard prueba",
 "description": "muestra el número de peticiones HTTP por segundo agrupadas por método, ruta y código de respuesta. Permite detectar picos de tráfico, rutas más usadas y errores en tiempo real.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "description": "muestra el número de peticiones HTTP por segundo agrupadas por método, ruta y código de respuesta. Permite detectar picos de tráfico, rutas más usadas y errores en tiempo real.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route, method) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia media por ruta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usuarios online",
   "type": "stat",
   "description": "Muestra en tiempo real el número de usuarios conectados a la plataforma en este momento.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "users_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Partidas activas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "games_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Conexiones al chat",
   "type": "stat",
   "description": "Número de usuarios actualmente conectados al sistema de chat en tiempo real, calculado como la diferencia entre conexiones totales y desconexiones.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chat_connections_total - chat_disconnects_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria head Node.js",
   "type": "timeseries",
   "description": " uso de memoria heap de Node.js a lo largo del tiempo. Permite detectar memory leaks o picos de consumo que puedan afectar al rendimiento del servidor.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}