input {
  tcp {
    port => 5001
    codec => json
  }
}

filter {
  mutate {
    add_field => { "service" => "backend" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ft-transcendence"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }

  stdout { codec => rubydebug }
}